StylesPath = styles
MinAlertLevel = suggestion

# 默认包
Packages = proselint, write-good, Readability

# 自定义规则目录
[formats]
mdx = md

# Markdown 文件
[*.md]
BasedOnStyles = Vale, proselint, write-good, Readability, custom

# PPTX 导出文本
[*.txt]
BasedOnStyles = Vale, custom

# 中英文混合规则
[formats]
mixed = md
